# Generated by Django 5.1.2 on 2024-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('assignedTo', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
